#!/usr/bin/env bash

echo "== list objects bucket"

if [ -z "$1" ]; then
  echo "There is need a bucket name .eg /bucket my-bucket-name."
  exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME