#!/usr/bin/env bash
echo "== sync"

set -e

if [ -z "$1" ]; then
  echo "There is need a bucket name .eg /bucket my-bucket-name."
  exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
  echo "There is need a bucket name .eg /bucket my-bucket-name. there need file name prefix"
  exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

OUTPUT_DIR="/tmp/s3-bash-script"

# remove folder if it already exist
# rm -r $OUTPUT_DIR

mkdir -p $OUTPUT_DIR


# Create between 5 and 10 files with random names
NUM_FILES=$((RANDOM % 6 + 5))

echo "📁 Creating $COUNT random files..."

for ((i=1; i<=$NUM_FILES; i++)); do

    random_filename="$OUTPUT_DIR/${FILENAME_PREFIX}_${i}.txt"

    dd if=/dev/urandom of="$random_filename" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null

done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files